apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey
  namespace: valkey
data:
  valkey.conf: |
    port 6379
  init-config.sh: |
    #!/bin/sh

    cp /etc/valkey/valkey.conf /tmp/valkey.conf
    cp /tmp/valkey.conf /config/valkey.conf

    mkdir -p /data
    chown -R 1000:1000 /data
