apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: valkey
  namespace: valkey
spec:
  namespaceSelector:
    matchNames:
      - valkey
  selector:
    matchLabels:
      app: valkey
  endpoints:
    - port: metrics
      interval: 30s
