# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ai-gateway
  namespace: cnpg-system
spec:
  name: ai_gateway
  owner: ai_gateway
  cluster:
    name: cloudnative-pg-cluster
  databaseReclaimPolicy: retain
