# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-web
  namespace: solar-panels
spec:
  selector:
    matchLabels:
      app: solar-web
  replicas: 1
  template:
    metadata:
      labels:
        app: solar-web
    spec:
      containers:
        - name: solar-web
          image: ghcr.io/accurate0/solar-web
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 15m
              memory: 16Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
