# SPDX-License-Identifier: MIT-0
---
# vars file for k3s-control
k3s_role: ""
k3s_systemd_service: "{{ 'k3s' if k3s_role == 'server' else 'k3s-agent' }}"
k3s_channel: "latest"
k3s_version: "v1.36.2+k3s1"
k3s_label_delegate_host: k8s-control-1
