# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-azure-unseal
  namespace: openbao
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-shared-vault
    kind: ClusterSecretStore
  target:
    name: openbao-azure-unseal
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        seal.hcl: |
          seal "azurekeyvault" {
            tenant_id     = "a41823d8-d908-4fa5-980a-cde6ae04d6ff"
            client_id     = "{{ .clientId }}"
            client_secret = "{{ .clientSecret }}"
            vault_name    = "k8s-shared-vault"
            key_name      = "openbao-unseal"
          }
  data:
    - secretKey: clientId
      remoteRef:
        key: openbao-azure-client-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: clientSecret
      remoteRef:
        key: openbao-azure-client-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
