# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./azure-unseal.externalsecret.yaml
configMapGenerator:
  - name: openbao-kanidm-icon
    files:
      - OpenBao.svg
generatorOptions:
  disableNameSuffixHash: true
