apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cloudnative-pg-cluster-daily-backup
  namespace: cnpg-system
spec:
  backupOwnerReference: self
  cluster:
    name: cloudnative-pg-cluster
  immediate: true
  method: barmanObjectStore
  schedule: 0 0 0 * * *
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
