apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: renovate-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mend-renovate-ce
  podMetricsEndpoints:
    - port: http
