#SPDX-License-Identifier: MIT-0
---
# tasks file for openebs
- name: Setup for openebs
  become: true
  become_user: root
  block:
    - name: Setup huge pages
      ansible.builtin.shell:
        cmd: "echo vm.nr_hugepages = 1024 | sudo tee -a /etc/sysctl.conf"
