# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/batch/cronjob_v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-schemas
  namespace: k8s-schemas
spec:
  schedule: "0 0 * * 0"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: k8s-schemas
          restartPolicy: OnFailure
          containers:
            - name: k8s-schemas
              image: ghcr.io/accurate0/k8s-schemas
              imagePullPolicy: Always
              env:
                - name: K8S_VERSION
                  value: v1.35.2
              envFrom:
                - secretRef:
                    name: k8s-schemas-managed-secrets
              resources:
                requests:
                  cpu: 50m
                  memory: 128Mi
                limits:
                  memory: 512Mi
