apiVersion: v1
kind: Service
metadata:
  name: anubis
  namespace: {{ .Values.namespace }}
  labels:
    app: anubis
spec:
  type: {{ .Values.service.type }}
  selector:
    app: anubis
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
