apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests
configMapGenerator:
  - name: ai-gateway-config
    namespace: ai-gateway
    files:
      - config.yaml
  - name: ai-gateway-dashboard
    namespace: ai-gateway
    files:
      - dashboards/ai-gateway.json
    options:
      disableNameSuffixHash: true
      labels:
        inf-k8s.net/grafana-dashboard: "true"
