apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozb-discord-bot
  namespace: ozbargain
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: ozb-discord-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: ozb-discord-bot
    spec:
      containers:
        - name: ozb-discord-bot
          image: ghcr.io/accurate0/ozb-discord-bot
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 15m
              memory: 16Mi
          envFrom:
            - secretRef:
                name: ozb-managed-secrets
