# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozb-discord-bot
  namespace: ozbargain
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: ozb-discord-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: ozb-discord-bot
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ozb-discord-bot
          image: ghcr.io/accurate0/ozb-discord-bot
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 15m
              memory: 16Mi
          envFrom:
            - secretRef:
                name: ozb-managed-secrets
