# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ozb-finder
  namespace: ozbargain
spec:
  selector:
    matchLabels:
      app: ozb-finder
  replicas: 1
  template:
    metadata:
      labels:
        app: ozb-finder
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ozb-finder
          image: ghcr.io/accurate0/ozb-finder
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 15m
              memory: 16Mi
          envFrom:
            - secretRef:
                name: ozb-managed-secrets
