apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - deployment.yaml
  - pricing-cronjob.yaml
  - secret.yaml
  - secretstore.yaml
  - service.yaml
  - servicemonitor.yaml
commonAnnotations:
  inf-k8s.net/app: ai-gateway
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/ai-gateway
    newTag: e5516783b4a18d0986fbe1c9a95207cb92e90fac
