apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - deployment.yaml
  - secret.yaml
  - secretstore.yaml
  - service.yaml
  - servicemonitor.yaml
commonAnnotations:
  inf-k8s.net/app: ai-gateway
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/ai-gateway
    newTag: 80248a96b21978665ea5b6b101e7caf0c7596670
