apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-gateway-managed-secrets
  namespace: ai-gateway
spec:
  refreshInterval: 900s
  secretStoreRef:
    name: infisical-ai-gateway-secret
    kind: SecretStore
  target:
    name: ai-gateway-managed-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: ".*"
        nullBytePolicy: Ignore
