apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api/api.deployment.yaml
  - web/web.deployment.yaml
  - scheduler/scheduler.deployment.yaml
  - recommendations/recommendations.service.yaml
  - recommendations/recommendations.deployment.yaml
  - api/api.service.yaml
  - namespace.yaml
  - web/web.service.yaml
  # - sensordata/sensordata.deployment.yaml
  # - sensordata/sensordata.service.yaml
  # - sensordata/pvc.yaml
images:
  - name: ghcr.io/accurate0/maccas-api
    newTag: c7f3758bda1aa90c4810f9779121b321c2ec8db3
  - name: ghcr.io/accurate0/maccas-clustering
    newTag: c7f3758bda1aa90c4810f9779121b321c2ec8db3
  - name: ghcr.io/accurate0/maccas-migration
    newTag: c7f3758bda1aa90c4810f9779121b321c2ec8db3
  - name: ghcr.io/accurate0/maccas-recommendations
    newTag: c7f3758bda1aa90c4810f9779121b321c2ec8db3
  - name: ghcr.io/accurate0/maccas-scheduler
    newTag: c7f3758bda1aa90c4810f9779121b321c2ec8db3
  - name: ghcr.io/accurate0/maccas-sensordata
    newTag: c7f3758bda1aa90c4810f9779121b321c2ec8db3
  - name: ghcr.io/accurate0/maccas-web
    newTag: c7f3758bda1aa90c4810f9779121b321c2ec8db3
