apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api/api.deployment.yaml
  - web/web.deployment.yaml
  - scheduler/scheduler.deployment.yaml
  - recommendations/recommendations.service.yaml
  - recommendations/recommendations.deployment.yaml
  - api/api.service.yaml
  - namespace.yaml
  - web/web.service.yaml
commonAnnotations:
  inf-k8s.net/app: maccas-api
  inf-k8s.net/repository: https://github.com/Accurate0/maccas-api
images:
  - name: ghcr.io/accurate0/maccas-api
    newTag: b66b64db86a59e09ca9bbb653fbde31c342b13e9
  - name: ghcr.io/accurate0/maccas-clustering
    newTag: b66b64db86a59e09ca9bbb653fbde31c342b13e9
  - name: ghcr.io/accurate0/maccas-migration
    newTag: b66b64db86a59e09ca9bbb653fbde31c342b13e9
  - name: ghcr.io/accurate0/maccas-recommendations
    newTag: b66b64db86a59e09ca9bbb653fbde31c342b13e9
  - name: ghcr.io/accurate0/maccas-scheduler
    newTag: b66b64db86a59e09ca9bbb653fbde31c342b13e9
  - name: ghcr.io/accurate0/maccas-sensordata
    newTag: b66b64db86a59e09ca9bbb653fbde31c342b13e9
  - name: ghcr.io/accurate0/maccas-web
    newTag: b66b64db86a59e09ca9bbb653fbde31c342b13e9
