# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/postgresdatabase_v1.json
apiVersion: inf-k8s.net/v1
kind: PostgresDatabase
metadata:
  name: feature-flags-database
  namespace: feature-flags
spec:
  databaseName: feature_flags
  secretName: feature-flags-database-secret
  secretNamespace: feature-flags
