# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/kanidmoauth2client_v1.json
apiVersion: inf-k8s.net/v1
kind: KanidmOAuth2Client
metadata:
  name: feature-flags
  namespace: feature-flags
spec:
  name: feature-flags
  displayName: Feature Flags
  origin: https://feature-flags.inf-k8s.net/
  redirectUrls:
    - https://feature-flags.inf-k8s.net/oauth2/callback
  preferShortUsername: true
  allowInsecureClientDisablePkce: true
  secretKeys:
    clientId: client-id
    clientSecret: client-secret
  scopeMaps:
    platform_admins:
      - openid
      - email
      - profile
  secretName: kanidm-feature-flags-oidc
  secretNamespace: feature-flags
