apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - daemonset.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - kanidmoauth2client.yaml
  - securitypolicy.yaml
  - secret.yaml
  - secretstore.yaml
  - service.yaml
commonAnnotations:
  inf-k8s.net/app: feature-flags
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/feature-flags
    newTag: 26e9c6a51d36b71e3e6fe2d8e22334a6c13776c0
  - name: ghcr.io/accurate0/feature-flags-frontend
    newTag: 26e9c6a51d36b71e3e6fe2d8e22334a6c13776c0
