apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - daemonset.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - service.yaml
commonAnnotations:
  inf-k8s.net/app: feature-flags
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/feature-flags
    newTag: 896cdcab52611ee2a1d857cecb9d4febca92d6a2
  - name: ghcr.io/accurate0/feature-flags-frontend
    newTag: ef611c17fa21f25f423dd22bef870fa944dd0b7c
