apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - daemonset.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - kanidmoauth2client.yaml
  - securitypolicy.yaml
  - secret.yaml
  - secretstore.yaml
  - service.yaml
commonAnnotations:
  inf-k8s.net/app: feature-flags
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/feature-flags
    newTag: 9f1690bed265cee05f55742640bb4463757198c8
  - name: ghcr.io/accurate0/feature-flags-frontend
    newTag: 78a5d776cbfee5d1661395d3bf607840fb920ed2
