# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: feature-flags
  namespace: feature-flags
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: feature-flags
  namespaceSelector:
    matchNames:
      - feature-flags
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
