name: Branch build k8s-schemas
on:
  workflow_dispatch:
  pull_request:
    paths:
      - platform-services/k8s-schemas/**
      - .forgejo/workflows/branch-build-k8s-schemas.yaml

jobs:
  build:
    name: Build
    runs-on: docker
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: platform-services/k8s-schemas
          load: true
          tags: scan:${{ github.sha }}
      - name: Install trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin
      - name: Trivy image scan
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed scan:${{ github.sha }}
