name: Branch build janitor-bot
on:
  workflow_dispatch:
  pull_request:
    paths:
      - platform-services/janitor-bot/**
      - .forgejo/workflows/branch-build-janitor-bot.yaml
  push:
    branches-ignore:
      - main
    paths:
      - platform-services/janitor-bot/**
      - .forgejo/workflows/branch-build-janitor-bot.yaml

jobs:
  build:
    name: Build
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./platform-services/janitor-bot
          push: false
          build-args: |
            BINARY_NAME=janitor-bot

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: platform-services/janitor-bot/target
          key: ${{ runner.os }}-app-target-${{ hashFiles('**/Cargo.lock') }}-janitor-bot
      - name: Install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - run: cargo test
        working-directory: platform-services/janitor-bot
