name: Publish helm charts
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - charts/**
      - .forgejo/workflows/publish-helm-charts.yaml

jobs:
  release:
    name: Release
    runs-on: docker
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.18.3

      - name: Install helm cm-push plugin
        run: helm plugin install https://github.com/chartmuseum/helm-push

      - name: Package and Publish
        env:
          FORGEJO_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          FORGEJO_URL: ${{ github.server_url }}
        run: |
          helm repo add --username "${OWNER}" --password "${FORGEJO_TOKEN}" \
            forgejo "${FORGEJO_URL}/api/packages/${OWNER}/helm"
          helm package charts/k8s-http-routes
          helm package charts/k8s-infisical-secrets
          for pkg in ./*.tgz; do
            helm cm-push --username "${OWNER}" --password "${FORGEJO_TOKEN}" "${pkg}" forgejo
          done
