# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-schemas
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  project: platform-services
  sources:
    - chart: k8s-secrets
      repoURL: oci://ghcr.io/accurate0/charts/k8s-secrets
      targetRevision: 0.3.0
      helm:
        valuesObject:
          defaults:
            namespace: k8s-schemas
            projectSlug: k8s-schemas-p-pb-y
            resyncInterval: 900
          secrets:
            - name: k8s-schemas-secret
              secretPath: /
              managedSecrets:
                - secretName: k8s-schemas-managed-secrets
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: platform-services/k8s-schemas/manifests
      kustomize:
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-schemas
