# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-sync-managed-secrets
  namespace: kanidm-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-shared-vault
    kind: ClusterSecretStore
  target:
    name: kanidm-sync-managed-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: KANIDM_TOKEN
      remoteRef:
        key: kanidm-provision-api-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
