apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.clusterrole.yaml
  - rbac.clusterrolebinding.yaml
  - externalsecret.yaml
  - deployment.yaml
commonAnnotations:
  inf-k8s.net/app: kanidm-sync
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/kanidm-sync
    newTag: 60fe7ccd1930f2ee88d726ef3799c5f1f6539223
