apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.clusterrole.yaml
  - rbac.clusterrolebinding.yaml
  - externalsecret.yaml
  - deployment.yaml
commonAnnotations:
  inf-k8s.net/app: kanidm-sync
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/kanidm-sync
    newTag: 37f8f01b7cd6c9788c1bc29e89caf4df06c9efc2
