apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
  project: default
  sources:
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: applications/postgres-cluster

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
