apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-cluster
  namespace: argocd
spec:
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/bootstrap/initdb/postInitApplicationSQL
        - /spec/managed
        - /spec/postgresql/shared_preload_libraries
        - /spec/priorityClassName
        - /spec/storage/storageClass
        - /spec/postgresql/pg_hba
        - /spec/postgresql/pg_ident
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: applications/postgres-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
