apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: descheduler
      repoURL: https://kubernetes-sigs.github.io/descheduler/
      targetRevision: 0.33.0
      helm:
        valuesObject:
          deschedulerPolicy:
            metricsProviders:
              - source: KubernetesMetrics
            profiles:
              - name: default
                pluginConfig:
                  - name: DefaultEvictor
                    args:
                      ignorePvcPods: true
                      evictLocalStoragePods: false
                  - name: RemoveDuplicates
                  - name: RemovePodsHavingTooManyRestarts
                    args:
                      podRestartThreshold: 100
                      includingInitContainers: true
                  - name: RemovePodsViolatingNodeAffinity
                    args:
                      nodeAffinityType:
                        - requiredDuringSchedulingIgnoredDuringExecution
                  - name: RemovePodsViolatingNodeTaints
                  - name: RemovePodsViolatingInterPodAntiAffinity
                  - name: RemovePodsViolatingTopologySpreadConstraint
                  - name: LowNodeUtilization
                    args:
                      thresholds:
                        cpu: 20
                        memory: 20
                        pods: 20
                      targetThresholds:
                        cpu: 50
                        memory: 50
                        pods: 50
                      metricsUtilization:
                        source: KubernetesMetrics
                  - name: "HighNodeUtilization"
                    args:
                      thresholds:
                        "cpu": 50
                        "memory": 50
                        "pods": 20
                plugins:
                  balance:
                    enabled:
                      - RemoveDuplicates
                      - RemovePodsViolatingTopologySpreadConstraint
                      - LowNodeUtilization
                      - HighNodeUtilization
                  deschedule:
                    enabled:
                      - RemovePodsHavingTooManyRestarts
                      - RemovePodsViolatingNodeTaints
                      - RemovePodsViolatingNodeAffinity
                      - RemovePodsViolatingInterPodAntiAffinity

  destination:
    server: https://kubernetes.default.svc
    namespace: descheduler

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
