apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  project: default
  sources:
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: applications/dragonfly
    - chart: dragonfly-operator
      # renovate: datasource=docker depName=ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator
      repoURL: oci://ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator
      targetRevision: v1.5.0
      helm:
        valuesObject:
          serviceMonitor:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: dragonfly-system

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
