apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        shared-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: k8s-http-routes
      repoURL: https://accurate0.github.io/inf-k8s
      targetRevision: 1.3.0
      helm:
        valuesObject:
          routes:
            - name: vault
              gateway:
                name: shared-gateway
                namespace: envoy-gateway-system
              hostnames:
                - vault.inf-k8s.net
              rules:
                - backendRefs:
                    - group: ""
                      kind: Service
                      name: infisical-infisical-standalone-infisical
                      port: 8080
                      weight: 1
                  matches:
                    - path:
                        type: PathPrefix
                        value: /
                - backendRefs:
                    - group: ""
                      kind: Service
                      name: infisical-infisical-standalone-infisical
                      port: 8080
                      weight: 1
                  matches:
                    - path:
                        type: Exact
                        value: /ss-webhook
    - chart: infisical-standalone
      repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
      targetRevision: 1.6.1
      helm:
        valuesObject:
          ingress:
            ingressClassName: nginx
            enabled: false
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx:
              enabled: false
            hostName: vault.inf-k8s.net
            tls:
              - secretName: vault-inf-k8s-tls
                hosts:
                  - vault.inf-k8s.net
          postgresql:
            enabled: false
          redis:
            enabled: false
          infisical:
            autoDatabaseSchemaMigration: true
            image:
              repository: infisical/infisical
              tag: "v0.96.1-postgres"
              pullPolicy: IfNotPresent
    - chart: secrets-operator
      repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
      targetRevision: 0.10.6

  destination:
    server: https://kubernetes.default.svc
    namespace: infisical

operation:
  sync:
    syncStrategy:
      hook: {}
