apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.13.0
      helm:
        valuesObject:
          controller:
            config:
              proxy-hide-headers: "Server, X-Powered-By"
              server-tokens: "False"
              enable-modsecurity: "False"
              use-proxy-protocol: "True"
              enable-owasp-modsecurity-crs: "True"
              enable-real-ip: "True"
              allow-snippet-annotations: "True"
              annotations-risk-level: Critical
              enable-opentelemetry: "false"
              opentelemetry-operation-name: "HTTP $request_method $service_name $uri"
              modsecurity-snippet: |
                SecRuleEngine DetectionOnly
                SecRequestBodyAccess On
                SecAuditLogFormat JSON
                SecAuditEngine On
                SecAuditLog /dev/stdout
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
            kind: DaemonSet

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
