apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - chart: ingress
      repoURL: https://charts.konghq.com
      targetRevision: 0.20.0
      helm:
        valuesObject:
          env:
            admin_gui_url: http://kong.inf-k8s.net
            admin_gui_api_url: http://kong-api.inf-k8s.net
            # Change the secret and set cookie_secure to true if using a HTTPS endpoint
            admin_gui_session_conf: '{"secret":"secret","storage":"kong","cookie_secure":true}'
          manager:
            enabled: true
            http:
              enabled: true
            tls:
              enabled: true

            ingress:
              enabled: true
              hostname: kong.inf-k8s.net
              path: /
              pathType: Prefix
              ingressClassName: kong

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
