apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-proxy
  namespace: envoy-gateway-system
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/name: envoy
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 15s
      scrapeTimeout: 10s
