apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robusta
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: robusta
  project: default
  sources:
    - chart: robusta
      repoURL: https://robusta-charts.storage.googleapis.com
      targetRevision: 0.21.5
      helm:
        valuesObject:
          clusterName: inf-k8s
          globalConfig:
            signing_key: "{{ env.SIGNING_KEY }}"
            account_id: "{{ env.ACCOUNT_ID }}"
          sinksConfig:
            - robusta_sink:
                name: robusta_ui_sink
                token: "{{ env.ROBUSTA_UI_SINK }}"
          enablePrometheusStack: false
          enablePlatformPlaybooks: true
          runner:
            additional_env_vars:
              - name: SIGNING_KEY
                valueFrom:
                  secretKeyRef:
                    name: robusta-managed-secret
                    key: SIGNING_KEY
              - name: ACCOUNT_ID
                valueFrom:
                  secretKeyRef:
                    name: robusta-managed-secret
                    key: ACCOUNT_ID
              - name: ROBUSTA_UI_SINK
                valueFrom:
                  secretKeyRef:
                    name: robusta-managed-secret
                    key: ROBUSTA_UI_SINK
                sendAdditionalTelemetry: true
          enableHolmesGPT: false
          enabledManagedConfiguration: true
          isSmallCluster: true
