apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: default
  sources:
    - repoURL: https://charts.signoz.io
      targetRevision: 0.88.1
      chart: signoz
      helm:
        valuesObject:
          clickhouse:
            persistence:
              storageClass: longhorn-local-perth
          global:
            storageClass: longhorn-local-perth
          signoz:
            ingress:
              enabled: true
              className: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - host: signoz.inf-k8s.net
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
                      port: 8080
              tls:
                - secretName: signoz-inf-k8s-tls
                  hosts:
                    - signoz.inf-k8s.net

  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
