apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: pool-on-k8s-optiplex-1
  namespace: openebs
spec:
  node: k8s-optiplex-1
  disks: ["aio:///dev/disk/by-id/ata-CT1000BX500SSD1_2420E8AF2852"]
---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: pool-on-k8s-optiplex-5
  namespace: openebs
spec:
  node: k8s-optiplex-5
  disks: ["aio:///dev/disk/by-id/ata-WD_Blue_SA510_2.5_1000GB_251434801288"]
