apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: flipt-secrets
  namespace: flipt-v2
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: flipt-v2-abs6
        envSlug: prod
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: flipt-managed-secrets
    secretNamespace: flipt-v2
    creationPolicy: "Owner"
