kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-single
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  fromBackup: ""
  fsType: "ext4"
reclaimPolicy: Retain
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-single-v2
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  dataLocality: best-effort
  numberOfReplicas: "1"
  fromBackup: ""
  fsType: "ext4"
reclaimPolicy: Retain
