apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: robusta-secret
  namespace: robusta
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: robusta-26-zk
        envSlug: prod
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedSecretReference:
    secretName: robusta-managed-secret
    secretNamespace: robusta
    creationPolicy: "Owner"
