apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-replica
parameters:
  protocol: nvmf
  repl: "2"
  allowVolumeExpansion: "true"
provisioner: io.openebs.csi-mayastor
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
parameters:
  recordsize: "128k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: "zfspv-pool"
provisioner: zfs.csi.openebs.io
allowedTopologies:
  - matchLabelExpressions:
      - key: kubernetes.io/hostname
        values:
          - k8s-optiplex-4
          - k8s-optiplex-2
