# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  namespace: argocd
spec:
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: firefly-app-key
      jsonPointers:
        - /data
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: firefly
      jqPathExpressions:
        - ".spec.rules[].backendRefs[].group"
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: firefly-importer
      jqPathExpressions:
        - ".spec.rules[].backendRefs[].group"
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  project: selfhosted
  sources:
    - chart: k8s-oidc
      repoURL: oci://ghcr.io/accurate0/charts/k8s-oidc
      targetRevision: 0.4.0
      helm:
        valuesObject:
          clients:
            - name: firefly
              namespace: firefly
              displayName: Firefly III
              host: firefly.inf-k8s.net
              preferShortUsername: true
              allowInsecureClientDisablePkce: true
              secretKeys:
                clientId: client-id
                clientSecret: client-secret
              secretName: kanidm-firefly-oidc
              secretNamespace: firefly
              securityPolicy:
                httpRoute: firefly
                scopes:
                  - openid
                  - email
                  - profile
                jwt:
                  cacheDuration: 3600s
                  idToken: true
                  claimToHeaders:
                    - claim: email
                      header: x-firefly-user-email
            - name: firefly-importer
              namespace: firefly
              displayName: Firefly III Importer
              host: firefly-importer.inf-k8s.net
              preferShortUsername: true
              allowInsecureClientDisablePkce: true
              secretKeys:
                clientId: client-id
                clientSecret: client-secret
              secretName: kanidm-firefly-importer-oidc
              secretNamespace: firefly
              securityPolicy:
                httpRoute: firefly-importer
                scopes:
                  - openid
                  - email
                  - profile
    - chart: k8s-postgres
      repoURL: oci://ghcr.io/accurate0/charts/k8s-postgres
      targetRevision: 1.0.1
      helm:
        valuesObject:
          databases:
            - name: firefly
              namespace: firefly
              databaseName: firefly
              secretName: firefly-db-credentials
    - chart: k8s-secrets
      repoURL: oci://ghcr.io/accurate0/charts/k8s-secrets
      targetRevision: 0.6.0
      helm:
        valuesObject:
          defaults:
            namespace: firefly
            provider: openbao
            resyncInterval: 900
          secrets:
            - name: firefly
              managedSecrets:
                - secretName: firefly-managed-secrets
            - name: integrations
              managedSecrets:
                - secretName: firefly-importer-managed-secrets
                  template:
                    includeAllSecrets: false
                    data:
                      accessToken: "{{ .FIREFLY_ACCESS_TOKEN }}"
                - secretName: firefly-up-sync-managed-secrets
                  template:
                    includeAllSecrets: false
                    data:
                      FIREFLY_TOKEN: "{{ .FIREFLY_ACCESS_TOKEN }}"
                      UP_TOKEN: "{{ .UP_TOKEN }}"
    - chart: firefly-iii
      repoURL: https://firefly-iii.github.io/kubernetes/
      targetRevision: 1.10.1
      helm:
        valuesObject:
          fullnameOverride: firefly

          image:
            tag: version-6.5.9

          replicaCount: 1
          deploymentStrategyType: Recreate

          podAnnotations:
            reloader.stakater.com/auto: "true"

          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  preference:
                    matchExpressions:
                      - key: inf-k8s.net/location
                        operator: In
                        values:
                          - perth

          persistence:
            enabled: true
            existingClaim: firefly-upload

          config:
            existingSecret: firefly-managed-secrets
            env:
              APP_URL: https://firefly.inf-k8s.net
              DB_CONNECTION: pgsql
              DB_HOST: cloudnative-pg-cluster-rw.cnpg-system
              DB_PORT: "5432"
              DEFAULT_LANGUAGE: en_US
              DEFAULT_LOCALE: equal
              TZ: Australia/Perth
              TRUSTED_PROXIES: "**"
              AUTHENTICATION_GUARD: remote_user_guard
              AUTHENTICATION_GUARD_HEADER: HTTP_X_FIREFLY_USER_EMAIL
              ALLOW_WEBHOOKS: "true"
              SITE_OWNER: contact@anurag.sh
            envValueFrom:
              DB_DATABASE:
                secretKeyRef:
                  name: firefly-db-credentials
                  key: PGDATABASE
              DB_USERNAME:
                secretKeyRef:
                  name: firefly-db-credentials
                  key: PGUSER
              DB_PASSWORD:
                secretKeyRef:
                  name: firefly-db-credentials
                  key: PGPASSWORD

          cronjob:
            enabled: true
            auth:
              existingSecret: firefly-managed-secrets
              secretKey: STATIC_CRON_TOKEN

          httpRoute:
            enabled: true
            hostnames:
              - firefly.inf-k8s.net
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: internal-gateway
                namespace: envoy-gateway-system

          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
    - chart: importer
      repoURL: https://firefly-iii.github.io/kubernetes/
      targetRevision: 1.6.0
      helm:
        valuesObject:
          fullnameOverride: firefly-importer

          image:
            tag: version-2.2.3

          replicaCount: 1

          podAnnotations:
            reloader.stakater.com/auto: "true"

          fireflyiii:
            url: http://firefly.firefly.svc.cluster.local
            vanityUrl: https://firefly.inf-k8s.net
            auth:
              existingSecret: firefly-importer-managed-secrets

          config:
            env:
              IGNORE_DUPLICATE_ERRORS: "true"
              IMPORT_DIR_ALLOWLIST: /var/www/html/storage/configurations,/var/www/html/storage/uploads
              TZ: Australia/Perth
            files:
              - mountPath: /var/www/html/storage/configurations
                name: amex-au.json
                content: |
                  {
                    "version": 3,
                    "source": "ff3-importer-2.2.3",
                    "created_at": "2026-10-07T23:50:00+08:00",
                    "date": "d/m/Y",
                    "default_account": 44,
                    "delimiter": "comma",
                    "headers": true,
                    "rules": true,
                    "webhooks": true,
                    "skip_form": false,
                    "add_import_tag": true,
                    "roles": [
                      "date_transaction",
                      "date_process",
                      "description",
                      "amount_negated",
                      "note",
                      "_ignore",
                      "_ignore",
                      "note",
                      "opposing-name",
                      "_ignore",
                      "_ignore",
                      "_ignore",
                      "_ignore",
                      "external-id"
                    ],
                    "do_mapping": [
                      false,
                      false,
                      false,
                      false,
                      false,
                      false,
                      false,
                      false,
                      false,
                      false,
                      false,
                      false,
                      false,
                      false
                    ],
                    "mapping": [],
                    "duplicate_detection_method": "cell",
                    "ignore_duplicate_lines": true,
                    "ignore_duplicate_transactions": true,
                    "unique_column_index": 13,
                    "unique_column_type": "external-id",
                    "flow": "file",
                    "content_type": "csv",
                    "custom_tag": "",
                    "identifier": "0",
                    "connection": "0",
                    "ignore_spectre_categories": false,
                    "grouped_transaction_handling": "",
                    "use_entire_opposing_address": false,
                    "map_all_data": false,
                    "accounts": [],
                    "date_range": "",
                    "date_range_number": 30,
                    "date_range_unit": "d",
                    "date_not_before": "",
                    "date_not_after": "",
                    "conversion": false
                  }

          httpRoute:
            enabled: true
            hostnames:
              - firefly-importer.inf-k8s.net
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: internal-gateway
                namespace: envoy-gateway-system

          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              memory: 512Mi
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: selfhosted/firefly
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: platform-services/firefly-up-sync/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
