# SPDX-License-Identifier: MIT-0
---
- name: Allow from K8S VPC for Binarylane
  community.general.ufw:
    rule: allow
    from: "{{ binarylane_vpc_cidr }}"

- name: Allow to K8S VPC for Binarylane
  community.general.ufw:
    rule: allow
    to: "{{ binarylane_vpc_cidr }}"
