# SPDX-License-Identifier: MIT-0
---
- name: Configure firewall
  become: true
  become_user: root
  block:
    - ansible.builtin.import_tasks: setup.yml
    - ansible.builtin.import_tasks: ssh.yml
      when: firewall_ratelimit_ssh
    - ansible.builtin.import_tasks: tailscale.yml
      when: firewall_allow_tailscale
    - ansible.builtin.import_tasks: cni.yml
      when: firewall_allow_cni
    - ansible.builtin.import_tasks: binarylane_vpc.yml
      when: firewall_binarylane_k8s_vpc
    - ansible.builtin.import_tasks: lan.yml
      when: firewall_allow_local_lan
    - ansible.builtin.import_tasks: web.yml

    - name: Reload ufw
      community.general.ufw:
        state: reloaded
