# SPDX-License-Identifier: MIT-0
---
- name: Install base packages
  become: true
  become_user: root
  community.general.pacman:
    update_cache: true
    name:
      - htop
      - nfs-utils
      - rsync
      - git
      - unzip
    state: present
