# SPDX-License-Identifier: MIT-0
---
- name: Disable PasswordAuthentication
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
  notify: Restart sshd
