# SPDX-License-Identifier: MIT-0
---
- name: Restart media stack
  become: true
  become_user: root
  community.docker.docker_compose_v2:
    project_src: "{{ media_config_root }}"
    state: restarted
