# SPDX-License-Identifier: MIT-0
---
proxmox_vfio_ids:
  - "1000:0097"

proxmox_vfio_blacklist:
  - mpt3sas

proxmox_vfio_modules:
  - vfio
  - vfio_iommu_type1
  - vfio_pci

proxmox_vfio_cmdline_params:
  - intel_iommu=on,sp_off
