{{- range .Values.secrets }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Values.defaults.namespace .namespace }}
  {{- if default $.Values.defaults.labels .labels}}
  labels:
    {{ default $.Values.defaults.labels .labels | toYaml | nindent 8 | trim }}
  {{- end}}

  {{- if default $.Values.defaults.annotations .annotations }}
  annotations:
    {{ default $.Values.defaults.annotations .annotations | toYaml | nindent 8 | trim }}
  {{- end }}
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: {{ default $.Values.defaults.resyncInterval .resyncInterval }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ default $.Values.defaults.projectSlug .projectSlug }}
        envSlug: prod
        secretsPath: {{ .secretPath }}
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    {{- range .managedSecrets  }}
    - secretName: {{ .secretName }}
      secretNamespace: {{ default $.Values.defaults.namespace .namespace }}
      creationPolicy: "Owner"
      secretType: Opaque
      {{- if .template }}
      template:
        {{ .template | toYaml | nindent 8 | trim }}
      {{- end }}
    {{- end }}
---
{{- end }}
