{{- range .Values.secrets }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .name }}
  namespace: {{ default $.Values.namespace .namespace }}
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: {{ .resyncInterval }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ default $.Values.projectSlug .projectSlug }}
        envSlug: prod
        secretsPath: {{ .secretPath }}
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    {{- range .managedSecrets  }}
    - secretName: {{ .secretName }}
      secretNamespace: {{ default $.Values.namespace .namespace }}
      creationPolicy: "Owner"
    {{- end }}
---
{{- end }}
