# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janitor-bot
  namespace: janitor-bot
spec:
  selector:
    matchLabels:
      app: janitor-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: janitor-bot
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: janitor-bot
          image: ghcr.io/accurate0/janitor-bot
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 60
          envFrom:
            - secretRef:
                name: janitor-bot-managed-secrets
          env:
            - name: FLIPT_URL
              value: http://flipt-v2.flipt-v2.svc.cluster.local:8080
            - name: ARGOCD_SERVER
              value: http://argocd-server.argocd.svc.cluster.local:80
            - name: OTEL_TRACING_URL
              value: http://monitoring-tempo.monitoring.svc.cluster.local:4318/v1/traces
