# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janitor-bot
  namespace: janitor-bot
spec:
  selector:
    matchLabels:
      app: janitor-bot
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: janitor-bot
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: {}
        - name: rules
          configMap:
            name: janitor-bot-rules
            items:
              - key: config.yaml
                path: config.yaml
              - key: manage-ci-image-updater.yaml
                path: rules/manage-ci-image-updater.yaml
              - key: manage-renovate.yaml
                path: rules/manage-renovate.yaml
              - key: automerge-renovate-terraform.yaml
                path: rules/automerge-renovate-terraform.yaml
              - key: manage-github-workflow.yaml
                path: rules/manage-github-workflow.yaml
              - key: retry-renovate-workflow.yaml
                path: rules/retry-renovate-workflow.yaml
              - key: argocd-diff-renovate.yaml
                path: rules/argocd-diff-renovate.yaml
              - key: mirror-commit-status.yaml
                path: rules/mirror-commit-status.yaml
              - key: argocd-sync-status.yaml
                path: rules/argocd-sync-status.yaml
              - key: forward-push-to-argocd.yaml
                path: rules/forward-push-to-argocd.yaml
              - key: clear-janitor-labels-on-merge.yaml
                path: rules/clear-janitor-labels-on-merge.yaml
              - key: clear-queued-on-unmergeable.yaml
                path: rules/clear-queued-on-unmergeable.yaml
      containers:
        - name: janitor-bot
          image: ghcr.io/accurate0/janitor-bot
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: rules
              mountPath: /etc/janitor-bot/rules
              readOnly: true
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 15
          envFrom:
            - secretRef:
                name: janitor-bot-managed-secrets
          env:
            - name: RULES_CONFIGMAP_PATH
              value: /etc/janitor-bot/rules/config.yaml
            - name: FEATURE_FLAGS_URL
              value: http://api.feature-flags.svc.cluster.local:50051
            - name: ARGOCD_SERVER
              value: http://argocd-server.argocd.svc.cluster.local:80
            - name: OTEL_TRACING_URL
              value: http://monitoring-tempo.monitoring.svc.cluster.local:4318/v1/traces
              # FIXME: use cluster local address
            - name: FORGEJO_INSTANCE_URL
              value: https://git.anurag.sh
