apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - secretstore.yaml
  - service.yaml
  - servicemonitor.yaml
commonAnnotations:
  inf-k8s.net/app: janitor-bot
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/janitor-bot
    newTag: e2c8ac8eca9c932e8bb35b0850305fefbf1b68a0
