apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - secretstore.yaml
  - service.yaml
  - servicemonitor.yaml
commonAnnotations:
  inf-k8s.net/app: janitor-bot
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/janitor-bot
    newTag: ee9ee787913ba49f0a0480fba229c3774f8b74d5
