apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - secretstore.yaml
  - service.yaml
  - servicemonitor.yaml
commonAnnotations:
  inf-k8s.net/app: janitor-bot
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/janitor-bot
    newTag: 5f8dd651b2b0241884ac7e2df677c44aa0899d6d
