apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: janitor-bot-managed-secrets
  namespace: janitor-bot
spec:
  refreshInterval: 900s
  secretStoreRef:
    name: infisical-janitor-bot-secret
    kind: ClusterSecretStore
  target:
    name: janitor-bot-managed-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: ".*"
        nullBytePolicy: Ignore
