# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: system-components
  sources:
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: system-components/envoy
    - chart: gateway-helm
      helm:
        valuesObject:
          deployment:
            replicas: 1
            envoyGateway:
              resources:
                limits:
                  cpu: 700m
                  memory: 256Mi
      path: gateway-helm
      repoURL: docker.io/envoyproxy
      targetRevision: 1.8.0
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
