# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        inf-k8s.net/infisical-secrets: "true"
        internal-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  project: system-components
  sources:
    - chart: k8s-secrets
      repoURL: oci://ghcr.io/accurate0/charts/k8s-secrets
      targetRevision: 0.3.0
      helm:
        valuesObject:
          defaults:
            namespace: longhorn-system
            projectSlug: longhorn-uc3e
            resyncInterval: 900
          secrets:
            - name: longhorn-backup-secrets
              secretPath: /
              managedSecrets:
                - secretName: longhorn-backup-credentials
                  template:
                    includeAllSecrets: false
                    data:
                      AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
                      AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
                      AWS_ENDPOINTS: "{{ .AWS_ENDPOINTS }}"
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: system-components/longhorn
    - chart: k8s-http-routes
      repoURL: oci://ghcr.io/accurate0/charts/k8s-http-routes
      targetRevision: 2.2.0
      helm:
        valuesObject:
          routes:
            - name: longhorn
              gateway:
                name: internal-gateway
                namespace: envoy-gateway-system
              hostnames:
                - longhorn.inf-k8s.net
              rules:
                - backendRefs:
                    - group: ""
                      kind: Service
                      name: longhorn-frontend
                      port: 80
                      weight: 1
                  matches:
                    - path:
                        type: PathPrefix
                        value: /
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.12.0
      helm:
        valuesObject:
          global:
            tolerations:
              - key: "inf-k8s.net/architecture"
                operator: "Equal"
                value: "arm64"
                effect: "NoSchedule"
          preUpgradeChecker:
            jobEnabled: false
            upgradeVersionCheck: false
          longhornUI:
            replicas: 1
          defaultBackupStore:
            backupTarget: s3://longhorn-backup@us-east-1/
            backupTargetCredentialSecret: longhorn-backup-credentials
          defaultSettings:
            taintToleration: inf-k8s.net/architecture=arm64:NoSchedule
          ingress:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

operation:
  initiatedBy:
    username: github-actions
  sync:
    syncStrategy:
      hook: {}
