# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        inf-k8s.net/infisical-secrets: "true"
        internal-gateway-access: "true"
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  project: system-components
  sources:
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: system-components/monitoring
    - chart: k8s-http-routes
      repoURL: oci://ghcr.io/accurate0/charts/k8s-http-routes
      targetRevision: 2.2.0
      helm:
        valuesObject:
          routes:
            - name: prometheus
              gateway:
                name: internal-gateway
                namespace: envoy-gateway-system
              hostnames:
                - prometheus.inf-k8s.net
              rules:
                - backendRefs:
                    - group: ""
                      kind: Service
                      name: monitoring-kube-prometheus-prometheus
                      port: 9090
                      weight: 1
                  matches:
                    - path:
                        type: PathPrefix
                        value: /
            - name: grafana
              gateway:
                name: internal-gateway
                namespace: envoy-gateway-system
              hostnames:
                - grafana.inf-k8s.net
              rules:
                - backendRefs:
                    - group: ""
                      kind: Service
                      name: monitoring-grafana
                      port: 80
                      weight: 1
                  matches:
                    - path:
                        type: PathPrefix
                        value: /
    - chart: k8s-secrets
      repoURL: oci://ghcr.io/accurate0/charts/k8s-secrets
      targetRevision: 0.3.0
      helm:
        valuesObject:
          defaults:
            namespace: monitoring
            projectSlug: monitoring-wg-xi
            resyncInterval: 900
          secrets:
            - name: monitoring-secrets
              secretPath: /
              managedSecrets:
                - secretName: monitoring-managed-secrets
    - chart: tempo
      repoURL: https://grafana-community.github.io/helm-charts
      targetRevision: 2.2.3
      helm:
        valuesObject:
          tempo:
            reportingEnabled: false
            retention: 336h
            metricsGenerator:
              enabled: true
              remoteWriteUrl: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
              processor:
                local_blocks:
                  flush_to_storage: true
                  filter_server_spans: false
                  max_block_duration: 1m
                service_graphs:
                  wait: 30s
                  max_items: 10000
                span_metrics:
                  enable_target_info: true
              storage:
                path: "/var/tempo/metrics"
              traces_storage:
                path: "/tmp/traces"
          persistence:
            enabled: true
            enableStatefulSetAutoDeletePVC: false
            storageClassName: longhorn-local-perth
            accessModes:
              - ReadWriteOnce
            size: 100Gi
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 87.0.1
      helm:
        valuesObject:
          prometheus:
            ingress:
              enabled: false
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - prometheus.inf-k8s.net
              tls:
                - secretName: prometheus-inf-k8s-tls
                  hosts:
                    - prometheus.inf-k8s.net
            prometheusSpec:
              otlp:
                promoteResourceAttributes:
                  - service.instance.id
                  - service.name
                  - service.namespace
                  - service.version
                  - cloud.availability_zone
                  - cloud.region
                  - container.name
                  - deployment.environment
                  - deployment.environment.name
                  - k8s.cluster.name
                  - k8s.container.name
                  - k8s.cronjob.name
                  - k8s.daemonset.name
                  - k8s.deployment.name
                  - k8s.job.name
                  - k8s.namespace.name
                  - k8s.pod.name
                  - k8s.replicaset.name
                  - k8s.statefulset.name
              tsdb:
                outOfOrderTimeWindow: 30m
              enableOTLPReceiver: true
              additionalScrapeConfigs:
                - job_name: "haproxy-metrics"
                  static_configs:
                    - targets:
                        - "100.98.212.43:8405"
                  tls_config:
                    insecure_skip_verify: true
              podMonitorSelectorNilUsesHelmValues: false
              probeSelectorNilUsesHelmValues: false
              ruleSelectorNilUsesHelmValues: false
              serviceMonitorSelectorNilUsesHelmValues: false
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: inf-k8s.net/location
                            operator: In
                            values:
                              - oracle-sydney
              tolerations:
                - key: "inf-k8s.net/architecture"
                  operator: "Equal"
                  value: "arm64"
                  effect: "NoSchedule"
              externalUrl: "https://prometheus.inf-k8s.net"
              retention: 2d
              retentionSize: "10GB"
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn-local
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 10Gi
          kubeEtcd:
            enabled: true
            endpoints:
              - 100.65.87.102
              - 100.70.180.118
              - 100.66.108.81
            service:
              enabled: true
              port: 2381
              targetPort: 2381
          alertmanager:
            enabled: false
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - alertmanager.inf-k8s.net
              tls:
                - secretName: alertmanager-inf-k8s-tls
                  hosts:
                    - alertmanager.inf-k8s.net
          alertmanagerSpec:
            alertmanagerConfigSelector:
              matchExpressions:
                - key: alertconfig
                  operator: In
                  values:
                    - discord-config
          grafana:
            envFromSecret: "monitoring-managed-secrets"
            sidecar:
              dashboards:
                enabled: true
                label: inf-k8s.net/grafana-dashboard
                labelValue: "true"
                searchNamespace: ALL
            envValueFrom:
              GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
                secretKeyRef:
                  name: kanidm-grafana-oidc
                  key: clientId
              GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
                secretKeyRef:
                  name: kanidm-grafana-oidc
                  key: clientSecret
            deploymentStrategy:
              type: Recreate
            grafana.ini:
              auth:
                disable_login_form: true
              auth.basic:
                enabled: false
              auth.generic_oauth:
                enabled: true
                allow_sign_up: true
                auto_login: true
                name: Kanidm
                scopes: openid profile email groups
                use_pkce: true
                use_refresh_token: true
                auth_url: https://idm.anurag.sh/ui/oauth2
                token_url: https://idm.anurag.sh/oauth2/token
                api_url: https://idm.anurag.sh/oauth2/openid/grafana/userinfo
                login_attribute_path: preferred_username
                groups_attribute_path: groups
                allow_assign_grafana_admin: true
                role_attribute_path: contains(grafana_role[*], 'GrafanaAdmin') && 'GrafanaAdmin' || contains(grafana_role[*], 'Editor') && 'Editor' || 'Viewer'
              server:
                root_url: "https://%(domain)s"
                domain: grafana.inf-k8s.net
                protocol: http
            # Provision grafana-dashboards-kubernetes
            dashboardProviders:
              dashboardproviders.yaml:
                apiVersion: 1
                providers:
                  - name: "grafana-dashboards-kubernetes"
                    orgId: 1
                    folder: "Kubernetes"
                    type: file
                    disableDeletion: true
                    editable: true
                    options:
                      path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
            dashboards:
              grafana-dashboards-kubernetes:
                k8s-system-api-server:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
                  token: ""
                k8s-system-coredns:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
                  token: ""
                k8s-views-global:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
                  token: ""
                k8s-views-namespaces:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
                  token: ""
                k8s-views-nodes:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
                  token: ""
                k8s-views-pods:
                  url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
                  token: ""
            persistence:
              enabled: true
              storageClassName: longhorn-single
              size: 1Gi
            ingress:
              enabled: false
              ingressClassName: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-prod
              hosts:
                - grafana.inf-k8s.net
              tls:
                - secretName: grafana-inf-k8s-tls
                  hosts:
                    - grafana.inf-k8s.net

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
