apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-gateway.secret.yaml
  - home-gateway.secretstore.yaml
  - home-gateway/home-gateway.deployment.yaml
  - home-gateway/home-gateway.service.yaml
  - home-gateway/home-gateway.servicemonitor.yaml
  - namespace.yaml
  - database.yaml
commonAnnotations:
  inf-k8s.net/app: home-gateway
  inf-k8s.net/repository: https://github.com/Accurate0/home-gateway
images:
  - name: ghcr.io/accurate0/home-gateway
    newTag: 727e9082dd0d1ab4f916248d26868c04f36d3d1a
