apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-gateway/home-gateway.deployment.yaml
  - home-gateway/home-gateway.service.yaml
  - home-gateway/home-gateway.servicemonitor.yaml
  - home-gateway/home-web.deployment.yaml
  - home-gateway/home-web.service.yaml
  - home-gateway/home-web.httproute.yaml
  - namespace.yaml
commonAnnotations:
  inf-k8s.net/app: home-gateway
  inf-k8s.net/repository: https://github.com/Accurate0/home-gateway
images:
  - name: ghcr.io/accurate0/home-gateway
    newTag: 97ccfacba17c77d9fb162c62c345d89846594d8b
  - name: ghcr.io/accurate0/home-gateway-web
    newTag: 449eec1372ef90300b95ee7215f00b75786c7943
