apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-gateway.secret.yaml
  - home-gateway.secretstore.yaml
  - home-gateway/home-gateway.deployment.yaml
  - home-gateway/home-gateway.service.yaml
  - home-gateway/home-gateway.servicemonitor.yaml
  - home-gateway/home-web.deployment.yaml
  - home-gateway/home-web.service.yaml
  - home-gateway/home-web.httproute.yaml
  - namespace.yaml
commonAnnotations:
  inf-k8s.net/app: home-gateway
  inf-k8s.net/repository: https://github.com/Accurate0/home-gateway
images:
  - name: ghcr.io/accurate0/home-gateway
    newTag: 4e4b0e9270a0b75b3254bab88ed5613c6abec445
  - name: ghcr.io/accurate0/home-gateway-web
    newTag: d9d545161ad391470903a1a0153b3a2d06e8dea2
