# SPDX-License-Identifier: MIT-0
---
- name: Reconcile node labels
  ansible.builtin.command:
    cmd: >-
      kubectl label node {{ k8s_node_name | default(inventory_hostname) }}
      {{ item.key }}={{ item.value }} --overwrite
  loop: "{{ node_labels | dict2items }}"
  delegate_to: "{{ k3s_label_delegate_host }}"
  changed_when: "'labeled' in label_result.stdout"
  register: label_result
  retries: 2
  delay: 3
  until: label_result is not failed
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: node_labels is defined
  ignore_errors: true
  ignore_unreachable: true
