# SPDX-License-Identifier: MIT-0
---
- name: Ensure valid vars
  ansible.builtin.assert:
    that:
      - "k3s_tailscale_auth_key != ''"
      - "k3s_role == 'agent' or k3s_role == 'server'"
      - "k3s_cluster_token != ''"
      - "k3s_channel != ''"
      - "k3s_version != ''"

- name: Get Service Status
  ansible.builtin.command: "tailscale ip -4"
  register: tailscale_ip_result
  tags:
    - skip_ansible_lint
