# SPDX-License-Identifier: MIT-0
---
- name: Restart seerr
  become: true
  become_user: root
  community.docker.docker_compose_v2:
    project_src: "{{ seerr_root }}"
    state: restarted
    remove_orphans: true
