nginx_domain: media.internal

nginx_sites:
  - {name: jellyfin, port: 8096}
  - {name: sonarr, port: 8989}
  - {name: radarr, port: 7878}
  - {name: transmission, port: 9091}
  - {name: flood, port: 3000}
  - {name: prowlarr, port: 9696}
  - {name: bazarr, port: 6767}
  - {name: flaresolverr, port: 8191}
  - {name: seerr, port: 5055}
