# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: public-gateway-client-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gateway
  proxyProtocol:
    optional: false
  clientIPDetection:
    customHeader:
      name: CF-Connecting-IP
      failClosed: false
  tcpKeepalive:
    probes: 9
    idleTime: "7200s"
    interval: "75s"
  tls:
    minVersion: "1.2"
  connection:
    connectionLimit:
      value: 50000
  http2:
    maxConcurrentStreams: 100
  headers:
    disableRateLimitHeaders: true
    earlyRequestHeaders:
      set:
        - name: "x-real-ip"
          value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
    lateResponseHeaders:
      set:
        - name: "x-request-id"
          value: "%REQ(x-request-id)%"
