# SPDX-License-Identifier: MIT-0
---
- name: Restart home-gateway-web stack
  become: true
  become_user: root
  community.docker.docker_compose_v2:
    project_src: "{{ home_gateway_web_root }}"
    state: restarted
    remove_orphans: true
