# SPDX-License-Identifier: MIT-0
---
homeassistant_root: /opt/homeassistant
homeassistant_image: ghcr.io/home-assistant/home-assistant
homeassistant_image_tag: "2026.7"
homeassistant_port: 80
homeassistant_timezone: Australia/Perth
