# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/postgresdatabase_v1.json
apiVersion: inf-k8s.net/v1
kind: PostgresDatabase
metadata:
  name: authentik-database
  namespace: authentik
spec:
  databaseName: authentik
  secretName: authentik-database-secret
  secretNamespace: authentik
