apiVersion: inf-k8s.net/v1
kind: PostgresDatabase
metadata:
  name: authentik-database
  namespace: authentik
spec:
  databaseName: authentik
  secretName: authentik-database-secret
  secretNamespace: authentik
