# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tldr-bot
  namespace: tldr-bot
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: tldr-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: tldr-bot
    spec:
      containers:
        - name: tldr-bot
          image: ghcr.io/accurate0/tldr-bot
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 15m
              memory: 16Mi
          envFrom:
            - secretRef:
                name: tldr-bot-managed-secrets
