apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
images:
  - name: ghcr.io/accurate0/tldr-bot
    newTag: 9418785de117e4f8869d01b3c967c4f5250dc97d
