apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - secretstore.yaml
commonAnnotations:
  inf-k8s.net/app: tldr-bot
  inf-k8s.net/repository: https://github.com/Accurate0/tldr-bot
images:
  - name: ghcr.io/accurate0/tldr-bot
    newTag: 5075ec0fc39464d2454f68aaffcce94d8c7b23f0
