# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/gateway.envoyproxy.io/envoyextensionpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: public-gateway-waf
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-gateway
  dynamicModule:
    - name: composer
      filterName: coraza-waf
      terminalFilter: false
      config:
        directives:
          - Include @coraza.conf
          - SecRuleEngine DetectionOnly
          - SecResponseBodyAccess Off
          - Include @crs-setup.conf
          - Include @owasp_crs/*.conf
