# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./daily-backup.recurringjob.yaml
  - ./kanidmoauth2client.yaml
  - ./longhorn-replicated-perth.yaml
  - ./securitypolicy.yaml
  - ./storageclasses
