{{- range $ns, $cfg := .Values.namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $ns }}-default-deny-ingress
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/managed-by: network-policies
spec:
  podSelector: {}
  policyTypes:
    - Ingress
{{- $ingress := append (default (list) $cfg.ingress) $ns }}
{{- if $ingress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $ns }}-allow-ingress
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/managed-by: network-policies
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
{{- range $entry := $ingress }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $entry }}
{{- end }}
{{- end }}
{{- end }}
