{{- $enabledRoutes := 0 }}

{{- range .Values.routes }}
  {{- if .crowdsecBouncer }}
    {{- $enabledRoutes = add $enabledRoutes 1 }}
  {{- end }}
{{- end }}

{{- if gt $enabledRoutes 0 -}}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ .Release.Name }}-crowdsec-bouncer-policy
spec:
  targetRefs:
  {{- range .Values.routes }}
    {{- if .crowdsecBouncer }}
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ .name }}
    {{- end }}
  {{- end }}
  extAuth:
    grpc:
      backendRefs:
        - group: ""
          kind: Service
          name: envoy-proxy-bouncer
          port: 8080
          namespace: envoy-proxy-bouncer
{{- end }}
