# SPDX-License-Identifier: MIT-0
---
- ansible.builtin.import_tasks: preflight.yml
- ansible.builtin.import_tasks: multipathd.yml
- ansible.builtin.import_tasks: install.yml
- ansible.builtin.import_tasks: config.yml
- ansible.builtin.import_tasks: labels.yml
