- name: Media server
  hosts: media_servers
  become: true
  gather_facts: true

  roles:
    - base
    - storage
    - nfs
    - docker
    - media
    - homeassistant
    - home-gateway-web
    - nginx
