# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/postgresdatabase_v1.json
apiVersion: inf-k8s.net/v1
kind: PostgresDatabase
metadata:
  name: pg-db-controller
  namespace: pg-db-controller
spec:
  databaseName: k8s_pg_db_controller
  secretName: pg-db-controller-test-secret
  secretNamespace: pg-db-controller
