# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db-controller
  namespace: pg-db-controller
spec:
  selector:
    matchLabels:
      app: pg-db-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-db-controller
    spec:
      serviceAccountName: pg-db-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: pg-db-controller
          image: ghcr.io/accurate0/pg-db-controller
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: pg-db-controller-managed-secrets
