apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.clusterrole.yaml
  - rbac.clusterrolebinding.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - secretstore.yaml
  - database.yaml
commonAnnotations:
  inf-k8s.net/app: pg-db-controller
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/pg-db-controller
    newTag: 64bed671f01ef572924863da732f71dd6d271f79
