apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-db-controller-managed-secrets
  namespace: pg-db-controller
spec:
  refreshInterval: 900s
  secretStoreRef:
    name: infisical-pg-db-controller-secret
    kind: ClusterSecretStore
  target:
    name: pg-db-controller-managed-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: ".*"
        nullBytePolicy: Ignore
