- name: Allow from K8S VPC for Binarylane
  community.general.ufw:
    rule: "{{ 'allow' if firewall_binarylane_k8s_vpc == true else 'deny' }}"
    from: "{{ binarylane_vpc_cidr }}"

- name: Allow to K8S VPC for Binarylane
  community.general.ufw:
    rule: "{{ 'allow' if firewall_binarylane_k8s_vpc == true else 'deny' }}"
    to: "{{ binarylane_vpc_cidr }}"
