# SPDX-License-Identifier: MIT-0
---
# tasks file for firewall
- name: Setup UFW
  become: true
  become_user: root
  block:
    - name: Install ufw
      ansible.builtin.apt:
        package:
          - ufw

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: allow
        logging: low

    - name: Ratelimit SSH
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Tailscale
      ansible.builtin.include_tasks:
        file: tailscale.yml

    - name: Binarylane vpc
      ansible.builtin.include_tasks:
        file: binarylane_vpc.yml

    - name: CNI
      ansible.builtin.include_tasks:
        file: cni.yml

    - name: Allow LAN for optiplex (Bunbury)
      community.general.ufw:
        rule: allow
        from: 192.168.1.0/24
      when: firewall_allow_local_lan

    - name: Allow LAN for optiplex (Bunbury)
      community.general.ufw:
        rule: allow
        to: 192.168.1.0/24
      when: firewall_allow_local_lan

    - name: Allow LAN for optiplex (Perth)
      community.general.ufw:
        rule: allow
        from: 10.0.1.0/24
      when: firewall_allow_local_lan

    - name: Allow LAN for optiplex (Perth)
      community.general.ufw:
        rule: allow
        to: 10.0.1.0/24
      when: firewall_allow_local_lan

    - name: Allow all outgoing
      community.general.ufw:
        rule: allow
        direction: out

    - name: Allow HTTPS
      ansible.builtin.include_tasks:
        file: https.yml

    - name: Allow all
      community.general.ufw:
        policy: allow

    - name: Reload ufw
      community.general.ufw:
        state: reloaded
