- name: Setup K3S
  hosts:
    - agent
    - control
  become: true
  gather_facts: false
  serial: 1

  roles:
    - role: k3s
      vars:
        k3s_role: "{{ 'agent' if 'agent' in group_names else 'server' }}"
        k3s_control_ip: https://100.78.166.71:6443
        k3s_tailscale_auth_key: "{{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }}"
        k3s_cluster_token: "{{ lookup('ansible.builtin.env', 'K3S_CLUSTER_TOKEN') }}"
        k3s_channel: "latest"
        k3s_version: "v1.34.1+k3s1"
