apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: mqcluster
spec:
  replicas: 3
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
    additionalConfig: |
      cluster_partition_handling = pause_minority
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storageClassName: longhorn-local-wait
    storage: "50Gi"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - mqcluster
          topologyKey: kubernetes.io/hostname
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: "inf-k8s.net/location"
                whenUnsatisfiable: ScheduleAnyway
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: mqcluster
