apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - database.yaml
images:
  - name: ghcr.io/accurate0/pg-db-controller
    newTag: feda10df8e1274ff2af44ea26883a160bd0226ad
