# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/postgresdatabase_v1.json
apiVersion: inf-k8s.net/v1
kind: PostgresDatabase
metadata:
  name: litellm-database
  namespace: litellm
spec:
  databaseName: litellm
  secretName: litellm-database-secret
  secretNamespace: litellm
