# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/kanidmoauth2client_v1.json
apiVersion: inf-k8s.net/v1
kind: KanidmOAuth2Client
metadata:
  name: litellm
  namespace: litellm
spec:
  name: litellm
  displayName: LiteLLM
  origin: https://litellm.inf-k8s.net/
  redirectUrls:
    - https://litellm.inf-k8s.net/sso/callback
  preferShortUsername: true
  allowInsecureClientDisablePkce: true
  secretKeys:
    clientId: GENERIC_CLIENT_ID
    clientSecret: GENERIC_CLIENT_SECRET
  scopeMaps:
    platform_admins:
      - openid
      - email
      - profile
      - groups
  secretName: kanidm-litellm-oidc
  secretNamespace: litellm
