# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar
  namespace: solar-panels
spec:
  selector:
    matchLabels:
      app: solar
  replicas: 1
  template:
    metadata:
      labels:
        app: solar
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: solar
          image: ghcr.io/accurate0/solar
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 15m
              memory: 32Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: HOME_GATEWAY_BASE_URL
              value: http://home-gateway.home-gateway.svc.cluster.local
            - name: OTEL_TRACING_URL
              value: http://monitoring-tempo.monitoring.svc.cluster.local:4318/v1/traces
          envFrom:
            - secretRef:
                name: solar-managed-secrets
            - secretRef:
                name: solar-database-secret
