# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-photon-data
  namespace: dawarich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-local
  resources:
    requests:
      storage: 400Gi
