# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/core/persistentvolumeclaim_v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-storage
  namespace: dawarich
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/daily-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-replicated
  resources:
    requests:
      storage: 20Gi
