{{- $defaults := .Values.defaults }}
{{- $hostAPI := default "http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api" $defaults.hostAPI }}
{{- $environmentSlug := default "prod" $defaults.environmentSlug }}
{{- $authSecretName := default "universal-auth-credentials" $defaults.authSecretName }}
{{- range $secret := .Values.secrets }}
{{- $storeName := printf "infisical-%s" $secret.name }}
{{- $namespace := default $defaults.namespace $secret.namespace }}
{{- $resync := default $defaults.resyncInterval $secret.resyncInterval }}
{{- $projectSlug := default $defaults.projectSlug $secret.projectSlug }}
{{- $secretPath := default "/" $secret.secretPath }}
{{- $recursive := default false $secret.recursive }}
{{- $labels := default $defaults.labels $secret.labels }}
{{- $annotations := default $defaults.annotations $secret.annotations }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $storeName }}
  namespace: {{ $namespace }}
spec:
  provider:
    infisical:
      hostAPI: {{ $hostAPI }}
      auth:
        universalAuthCredentials:
          clientId:
            name: {{ $authSecretName }}
            key: clientId
          clientSecret:
            name: {{ $authSecretName }}
            key: clientSecret
      secretsScope:
        projectSlug: {{ $projectSlug }}
        environmentSlug: {{ $environmentSlug }}
        secretsPath: {{ $secretPath }}
        recursive: {{ $recursive }}
---
{{- range $managed := $secret.managedSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $managed.secretName }}
  namespace: {{ $namespace }}
  {{- if $labels }}
  labels:
    {{ $labels | toYaml | nindent 4 | trim }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{ $annotations | toYaml | nindent 4 | trim }}
  {{- end }}
spec:
  refreshInterval: {{ $resync }}s
  secretStoreRef:
    name: {{ $storeName }}
    kind: SecretStore
  target:
    name: {{ $managed.secretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      {{- if or $labels $annotations }}
      metadata:
        {{- if $labels }}
        labels:
          {{ $labels | toYaml | nindent 10 | trim }}
        {{- end }}
        {{- if $annotations }}
        annotations:
          {{ $annotations | toYaml | nindent 10 | trim }}
        {{- end }}
      {{- end }}
      {{- if $managed.template }}
      engineVersion: v2
      mergePolicy: Replace
      data:
        {{- range $k, $v := $managed.template.data }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- end }}
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: ".*"
        nullBytePolicy: Ignore
---
{{- end }}
{{- end }}
