{{- range $secret := .Values.secrets }}
{{- $storeName := printf "infisical-%s" $secret.name }}
{{- $namespace := default $.Values.defaults.namespace $secret.namespace }}
{{- $resync := default $.Values.defaults.resyncInterval $secret.resyncInterval }}
{{- $labels := default $.Values.defaults.labels $secret.labels }}
{{- $annotations := default $.Values.defaults.annotations $secret.annotations }}
{{- range $managed := $secret.managedSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $managed.secretName }}
  namespace: {{ $namespace }}
  {{- if $labels }}
  labels:
    {{ $labels | toYaml | nindent 4 | trim }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{ $annotations | toYaml | nindent 4 | trim }}
  {{- end }}
spec:
  refreshInterval: {{ $resync }}s
  secretStoreRef:
    name: {{ $storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ $managed.secretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      {{- if $managed.template }}
      engineVersion: v2
      mergePolicy: Replace
      data:
        {{- range $k, $v := $managed.template.data }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
      {{- end }}
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: ".*"
        nullBytePolicy: Ignore
---
{{- end }}
{{- end }}
