apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - database.yaml
images:
  - name: ghcr.io/accurate0/pg-db-controller
    newTag: 2a7863db23c883c0105b4b52671d8bc34f7e016f
