# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maccas-recommendations
  namespace: maccas-api
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: maccas-recommendations
  replicas: 1
  template:
    metadata:
      labels:
        app: maccas-recommendations
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: maccas-migration
          image: ghcr.io/accurate0/maccas-migration
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          envFrom:
            - secretRef:
                name: maccas-migration-managed-secrets
      containers:
        - name: maccas-recommendations
          image: ghcr.io/accurate0/maccas-recommendations
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: 800Mi
              cpu: 150m
            limits:
              memory: 1000Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8003
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          env:
            - name: FLIPT_URL
              value: http://flipt.flipt.svc.cluster.local:8080
            - name: CLUSTERING_API_BASE
              value: http://maccas-recommendations.maccas-api.svc.cluster.local:8004
            - name: OTEL_TRACING_URL
              value: http://monitoring-tempo.monitoring.svc.cluster.local:4318/v1/traces
          envFrom:
            - secretRef:
                name: maccas-common-managed-secrets
            - secretRef:
                name: maccas-api-managed-secrets
          ports:
            - containerPort: 8003
        - name: maccas-clustering
          image: ghcr.io/accurate0/maccas-clustering
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 192Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8004
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: maccas-common-managed-secrets
            - secretRef:
                name: maccas-api-managed-secrets
          ports:
            - containerPort: 8004
