# SPDX-License-Identifier: MIT-0
---
- name: Rebuild the initramfs
  become: true
  become_user: root
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true

- name: Refresh the boot configuration
  become: true
  become_user: root
  ansible.builtin.command: proxmox-boot-tool refresh
  changed_when: true
