# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/postgresdatabase_v1.json
apiVersion: inf-k8s.net/v1
kind: PostgresDatabase
metadata:
  name: bom-database
  namespace: bom
spec:
  databaseName: bom
  secretName: bom-database-secret
  secretNamespace: bom
