apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - database.yaml
images:
  - name: ghcr.io/accurate0/bom
    newTag: d26bdc7dd4e180653747cef713703f33de41a6b1
