apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - database.yaml
commonAnnotations:
  inf-k8s.net/repository: "https://github.com/Accurate0/bom"
  inf-k8s.net/app: "bom"
images:
  - name: ghcr.io/accurate0/bom
    newTag: 03afdf34e91a6748600b247ac7ffe361071a684d
