apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - database.yaml
images:
  - name: ghcr.io/accurate0/bom
    newTag: cef19d01c8d9a74d8bd9313e4892b6aaee8dd459
