# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfbot
  namespace: home-gateway
  annotations:
    secrets.infisical.com/auto-reload: "true"
spec:
  selector:
    matchLabels:
      app: selfbot
  replicas: 1
  template:
    metadata:
      labels:
        app: selfbot
    spec:
      containers:
        - name: selfbot
          image: ghcr.io/accurate0/home-selfbot
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 15m
              memory: 128Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8004
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: selfbot-managed-secrets
          ports:
            - containerPort: 3000
