# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-home
  namespace: ingress-home
spec:
  selector:
    matchLabels:
      app: ingress-home
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-home
    spec:
      serviceAccountName: ingress-home
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ingress-home
          image: ghcr.io/accurate0/ingress-home
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
          ports:
            - containerPort: 3000
