# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-home
  namespace: ingress-home
spec:
  selector:
    matchLabels:
      app: ingress-home
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-home
    spec:
      serviceAccountName: ingress-home
      containers:
        - name: ingress-home
          image: ghcr.io/accurate0/ingress-home
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 15m
              memory: 16Mi
          ports:
            - containerPort: 3000
