# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/kanidmoauth2client_v1.json
apiVersion: inf-k8s.net/v1
kind: KanidmOAuth2Client
metadata:
  name: ingress-home
  namespace: ingress-home
spec:
  name: ingress-home
  displayName: Home
  origin: https://inf-k8s.net/
  redirectUrls:
    - https://inf-k8s.net/oauth2/callback
  preferShortUsername: true
  allowInsecureClientDisablePkce: true
  secretKeys:
    clientId: client-id
    clientSecret: client-secret
  scopeMaps:
    platform_admins:
      - openid
      - email
      - profile
  secretName: kanidm-ingress-home-oidc
  secretNamespace: ingress-home
