apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - kanidmoauth2client.yaml
  - rbac.clusterrole.yaml
  - rbac.clusterrolebinding.yaml
  - namespace.yaml
  - securitypolicy.yaml
  - service.yaml
  - serviceaccount.yaml
commonAnnotations:
  inf-k8s.net/app: ingress-home
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/ingress-home
    newTag: b566f95bb8ca76449fcb0568630aa4d1d6e5beeb
