apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-shared-vault
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://k8s-shared-vault.vault.azure.net
      tenantId: a41823d8-d908-4fa5-980a-cde6ae04d6ff
      authSecretRef:
        clientId:
          name: k8s-shared-vault-creds
          key: clientId
          namespace: external-secrets
        clientSecret:
          name: k8s-shared-vault-creds
          key: clientSecret
          namespace: external-secrets
