apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-shared-vault-creds
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-shared-vault-creds
    kind: SecretStore
  target:
    name: k8s-shared-vault-creds
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: clientId
      remoteRef:
        key: AZURE_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: AZURE_CLIENT_SECRET
