- name: Base
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: base
      become: true
      become_method: sudo
      become_user: root
    - role: tailscale
      vars:
        tailscale_join_network: false

- name: Setup K3S
  hosts:
    - agent
    - control
  become: true
  gather_facts: false
  serial: 1

  roles:
    - role: tailscale
      vars:
        tailscale_join_network: true
        tailscale_auth_key: "{{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }}"
    - role: firewall
      vars:
        firewall_allow_http: false
        firewall_binarylane_k8s_vpc: true
        firewall_allow_local_lan: true
      when: "inventory_hostname == 'oracle'"
    - role: k3s
      vars:
        k3s_role: "{{ 'agent' if 'agent' in group_names else 'server' }}"
        k3s_tailscale_auth_key: "{{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }}"
        k3s_cluster_token: "{{ lookup('ansible.builtin.env', 'K3S_CLUSTER_TOKEN') }}"

- name: Setup proxy servers
  hosts: proxy
  become: true
  serial: 1

  roles:
    - role: firewall
    - role: tailscale
      vars:
        tailscale_join_network: true
        tailscale_auth_key: "{{ lookup('ansible.builtin.env', 'TAILSCALE_K8S_AUTH_KEY') }}"
    - role: edge-proxy
