apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml
commonAnnotations:
  inf-k8s.net/repository: "https://github.com/Accurate0/inf-k8s"
  inf-k8s.net/app: "ingress-home"
images:
  - name: ghcr.io/accurate0/ingress-home
    newTag: a81b0fcc49650006959cbfbad4cc2c5225357977
