apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml
images:
  - name: ghcr.io/accurate0/ingress-home
    newTag: 00bdde50f0d9ced37610133f1ef0e916017ae7c5
