apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.clusterrole.yaml
  - rbac.clusterrolebinding.yaml
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml
commonAnnotations:
  inf-k8s.net/app: ingress-home
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/ingress-home
    newTag: cf5e027299091d8bcb1d371d73a5cca7ad7aef67
