# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-flags
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  project: platform-services
  sources:
    - chart: k8s-oidc
      repoURL: oci://ghcr.io/accurate0/charts/k8s-oidc
      targetRevision: 0.2.2
      helm:
        valuesObject:
          clients:
            - name: feature-flags
              namespace: feature-flags
              displayName: Feature Flags
              host: feature-flags.inf-k8s.net
              preferShortUsername: true
              allowInsecureClientDisablePkce: true
              secretKeys:
                clientId: client-id
                clientSecret: client-secret
              scopeMaps:
                platform_admins:
                  - openid
                  - email
                  - profile
              secretName: kanidm-feature-flags-oidc
              secretNamespace: feature-flags
              annotations:
                inf-k8s.net/app: feature-flags
                inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
              securityPolicy:
                httpRoute: feature-flags-frontend
                scopes:
                  - openid
                  - email
                  - profile
                forwardAccessToken: true
                jwt:
                  cacheDuration: 3600s
    - chart: k8s-postgres
      repoURL: oci://ghcr.io/accurate0/charts/k8s-postgres
      targetRevision: 0.2.0
      helm:
        valuesObject:
          databases:
            - name: feature-flags
              namespace: feature-flags
              databaseName: feature_flags
              secretName: feature-flags-database-secret
              secretNamespace: feature-flags
              annotations:
                inf-k8s.net/app: feature-flags
                inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      path: platform-services/feature-flags/manifests
    - chart: k8s-http-routes
      repoURL: oci://ghcr.io/accurate0/charts/k8s-http-routes
      targetRevision: 2.3.1
      helm:
        valuesObject:
          routes:
            - name: feature-flags-frontend
              gateway:
                name: internal-gateway
                namespace: envoy-gateway-system
              hostnames:
                - feature-flags.inf-k8s.net
              rules:
                - backendRefs:
                    - group: ""
                      kind: Service
                      name: frontend
                      port: 80
                      weight: 1
                  matches:
                    - path:
                        type: PathPrefix
                        value: /
  destination:
    server: https://kubernetes.default.svc
    namespace: feature-flags
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
