apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-replicator-infisical
spec:
  provider:
    kubernetes:
      remoteNamespace: infisical
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: external-secrets
      auth:
        serviceAccount:
          name: universal-auth-replicator
          namespace: infisical
