apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: universal-auth-credentials
spec:
  externalSecretName: universal-auth-credentials
  namespaceSelectors:
    - matchLabels:
        inf-k8s.net/infisical-secrets: "true"
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: k8s-replicator-infisical
      kind: ClusterSecretStore
    target:
      name: universal-auth-credentials
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: universal-auth-credentials
