apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - database.yaml
  - service.yaml
commonAnnotations:
  inf-k8s.net/repository: "https://github.com/Accurate0/solar-panels"
  inf-k8s.net/app: "solar-panels"
images:
  - name: ghcr.io/accurate0/solar
    newTag: 57a4e1815dc77e946e867cf8c66ba069f6ea38cc
  - name: ghcr.io/accurate0/solar-web
    newTag: 57a4e1815dc77e946e867cf8c66ba069f6ea38cc
