apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - solar/solar.deployment.yaml
  - solar/solar.service.yaml
  - solar-web/solar-web.deployment.yaml
  - solar-web/solar-web.service.yaml
  - namespace.yaml
  - secret.yaml
  - secretstore.yaml
  - database.yaml
commonAnnotations:
  inf-k8s.net/app: solar-panels
  inf-k8s.net/repository: https://github.com/Accurate0/solar-panels
images:
  - name: ghcr.io/accurate0/solar
    newTag: 146de31eea698dcd32f896e33e6bc5b1f2eced69
  - name: ghcr.io/accurate0/solar-web
    newTag: 2f40e941d124b3180eaaffecc3010d720eacf78e
