apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - solar/solar.deployment.yaml
  - solar/solar.service.yaml
  - solar-web/solar-web.deployment.yaml
  - solar-web/solar-web.service.yaml
  - namespace.yaml
  - secret.yaml
  - secretstore.yaml
  - database.yaml
commonAnnotations:
  inf-k8s.net/app: solar-panels
  inf-k8s.net/repository: https://github.com/Accurate0/solar-panels
images:
  - name: ghcr.io/accurate0/solar
    newTag: 4d5919b362df4ba5630d6347bd181d49ba2dabdc
  - name: ghcr.io/accurate0/solar-web
    newTag: 4d5919b362df4ba5630d6347bd181d49ba2dabdc
