apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: solar-managed-secrets
  namespace: solar-panels
spec:
  refreshInterval: 900s
  secretStoreRef:
    name: infisical-solar-secret
    kind: ClusterSecretStore
  target:
    name: solar-managed-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: ".*"
        nullBytePolicy: Ignore
