apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
images:
  - name: ghcr.io/accurate0/anurag-sh
    newTag: 4d1d4c385bfdea1d197df71fb415be13d48d5cd6
