apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
commonAnnotations:
  inf-k8s.net/app: anurag-sh
  inf-k8s.net/repository: https://github.com/Accurate0/anurag.sh
images:
  - name: ghcr.io/accurate0/anurag-sh
    newTag: 314dd28f39ef35bf8a03b333b1f9f758eb356ed7
