all:
  children:
    proxmox: {}
    media_servers: {}
    gateway: {}
    home_automation: {}

proxmox:
  hosts:
    pve:
      ansible_host: 10.0.2.249

media_servers:
  hosts:
    jellyfin:
      ansible_host: 10.0.2.11
    media-apps:
      ansible_host: 10.0.2.12
    transmission:
      ansible_host: 10.0.2.13
  vars:
    media_pool_mount: /data

gateway:
  hosts:
    home-gateway-web:
      ansible_host: 10.0.2.14

home_automation:
  hosts:
    homeassistant:
      ansible_host: 10.0.2.15
