apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flipt-managed-secrets
  namespace: flipt-v2
spec:
  refreshInterval: 900s
  secretStoreRef:
    name: infisical-flipt-secrets
    kind: ClusterSecretStore
  target:
    name: flipt-managed-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - find:
        name:
          regexp: ".*"
