# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/kanidmoauth2client_v1.json
apiVersion: inf-k8s.net/v1
kind: KanidmOAuth2Client
metadata:
  name: flipt
  namespace: flipt-v2
spec:
  name: flipt
  displayName: Flipt
  origin: https://flipt.inf-k8s.net/
  redirectUrls:
    - https://flipt.inf-k8s.net/auth/v1/method/oidc/kanidm/callback
  preferShortUsername: true
  allowInsecureClientDisablePkce: true
  enableLegacyCrypto: true
  secretKeys:
    clientId: FLIPT_KANIDM_CLIENT_ID
    clientSecret: FLIPT_KANIDM_CLIENT_SECRET
    issuerUrl: FLIPT_KANIDM_ISSUER_URL
  scopeMaps:
    flipt_users:
      - openid
      - email
      - profile
      - groups
    platform_admins:
      - openid
      - email
      - profile
      - groups
  secretName: kanidm-flipt-oidc
  secretNamespace: flipt-v2
  icon:
    configMap: flipt-kanidm-icon
    key: Flipt.svg
