# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flipt-v2.secret.yaml
  - ./secretstore.yaml
  - ./kanidmoauth2client.yaml
configMapGenerator:
  - name: flipt-kanidm-icon
    files:
      - Flipt.svg
generatorOptions:
  disableNameSuffixHash: true
