media_drives: []
media_pool_mount: /data/media
media_config_root: /opt/media

media_disks_root: /data/disks
media_pool_options: >-
  defaults,allow_other,cache.files=partial,dropcacheonclose=true,category.create=mfs,never-forget-nodes=true,inodecalc=path-hash,lazy-umount-mountpoint=false

media_puid: 1000
media_pgid: 1000

media_apps:
  - jellyfin
  - sonarr
  - radarr
  - transmission
  - flood
  - prowlarr
  - bazarr
