vpn-auth: "name=tailscale,joinKey={{ k3s_tailscale_auth_key }}"
node-external-ip: "{{ tailscale_ip.stdout }}"
node-ip: "{{ tailscale_ip.stdout }}"
server: "{{ k3s_control_ip }}"
token: "{{ k3s_cluster_token }}"
kubelet-arg:
  - "image-gc-high-threshold=50"
  - "image-gc-low-threshold=20"
  - "maximum-dead-containers=0"
