apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - certificate.yaml
  - httproute.yaml
  - backendtlspolicy.yaml
  - groups/argocd-users.yaml
  - groups/dawarich-users.yaml
  - groups/flipt-users.yaml
  - groups/forgejo-users.yaml
  - groups/grafana-users.yaml
  - groups/platform-admins.yaml
  - users/anurag.yaml
