apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - service-headless.yaml
  - serviceaccount.yaml
  - rbac.role.yaml
  - rbac.rolebinding.yaml
  - pdb.yaml
  - certificate.yaml
  - httproute.yaml
  - backendtlspolicy.yaml
  - backend.policy.yaml
  - groups/platform-admins.yaml
  - users/anurag.yaml

configMapGenerator:
  - name: kanidm-coordinator
    files:
      - coordinator/bootstrap.sh
    options:
      disableNameSuffixHash: true
  - name: proxmox-kanidm-icon
    files:
      - Proxmox.svg
    options:
      disableNameSuffixHash: true
