apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - service-headless.yaml
  - serviceaccount.yaml
  - rbac.role.yaml
  - rbac.rolebinding.yaml
  - certificate.yaml
  - httproute.yaml
  - backendtlspolicy.yaml
  - clients/pbs.yaml
  - clients/pve.yaml
  - groups/argocd-users.yaml
  - groups/dawarich-users.yaml
  - groups/flipt-users.yaml
  - groups/forgejo-users.yaml
  - groups/grafana-users.yaml
  - groups/home-gateway-admins.yaml
  - groups/home-gateway-readers.yaml
  - groups/platform-admins.yaml
  - users/anurag.yaml

configMapGenerator:
  - name: kanidm-coordinator
    files:
      - coordinator/bootstrap.sh
    options:
      disableNameSuffixHash: true
