# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/policy/poddisruptionbudget_v1.json
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kanidm
  labels:
    app.kubernetes.io/name: kanidm
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kanidm
