# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backend.policy.yaml
  - ./bootstrap.appproject.yaml
  - ./default.appproject.yaml
  - ./platform-services.appproject.yaml
  - ./projects.appproject.yaml
  - ./selfhosted.appproject.yaml
  - ./system-components.appproject.yaml
  - ./platform-services-apps.application.yaml
  - ./projects-apps.application.yaml
  - ./selfhosted-apps.application.yaml
  - ./system-components-apps.application.yaml
  - ./kanidmoauth2client.yaml
configMapGenerator:
  - name: argocd-kanidm-icon
    files:
      - ArgoCD.svg
generatorOptions:
  disableNameSuffixHash: true
