# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/apps/deployment_v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janitor-bot
  namespace: janitor-bot
spec:
  selector:
    matchLabels:
      app: janitor-bot
  replicas: 1
  template:
    metadata:
      annotations:
        secrets.infisical.com/auto-reload: "true"
      labels:
        app: janitor-bot
    spec:
      containers:
        - name: janitor-bot
          image: ghcr.io/accurate0/janitor-bot
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 15m
              memory: 16Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 60
          envFrom:
            - secretRef:
                name: janitor-bot-managed-secrets
          env:
            - name: FLIPT_URL
              value: http://flipt-v2.flipt-v2.svc.cluster.local:8080
