apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
images:
  - name: ghcr.io/accurate0/janitor-bot
    newTag: 6642e2b8577dd4619764e11d8e2aca4b268ca76d
