apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
images:
  - name: ghcr.io/accurate0/janitor-bot
    newTag: 125fcc2470ffea15c185557b8849af087f3ad965
