apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - securitypolicy.yaml
commonAnnotations:
  inf-k8s.net/app: janitor-bot
  inf-k8s.net/repository: https://github.com/Accurate0/inf-k8s
images:
  - name: ghcr.io/accurate0/janitor-bot
    newTag: 917571dfe3248d38c93155d7225a6ef65617880c
