apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: janitor-bot-secret
  namespace: janitor-bot
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: janitor-bot-vtsj
        envSlug: prod
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: janitor-bot-managed-secrets
      secretNamespace: janitor-bot
      creationPolicy: "Owner"
      secretType: Opaque
