# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: janitor-bot
spec:
  selector:
    app: janitor-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
