# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/kanidmoauth2client_v1.json
apiVersion: inf-k8s.net/v1
kind: KanidmOAuth2Client
metadata:
  name: grafana
  namespace: monitoring
spec:
  name: grafana
  displayName: Grafana
  origin: https://grafana.inf-k8s.net/
  redirectUrls:
    - https://grafana.inf-k8s.net/login/generic_oauth
  scopeMaps:
    grafana_users:
      - openid
      - email
      - profile
      - groups
    platform_admins:
      - openid
      - email
      - profile
      - groups
  secretName: kanidm-grafana-oidc
  secretNamespace: monitoring
