apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-gateway
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  project: default
  sources:
    - chart: k8s-http-routes
      repoURL: oci://ghcr.io/accurate0/charts/k8s-http-routes
      targetRevision: 2.1.0
      helm:
        valuesObject:
          routes:
            - name: api-route
              gateway:
                name: shared-gateway
                namespace: envoy-gateway-system
              hostnames:
                - home.anurag.sh
              ratelimit:
                rules:
                  - clientSelectors:
                      - headers:
                          - name: CF-Connecting-IP
                            type: Distinct
                            invert: false
                    limit:
                      requests: 5
                      unit: Second
              rules:
                - backendRefs:
                    - group: ""
                      kind: Service
                      name: home-gateway
                      port: 80
                      weight: 1
                  matches:
                    - path:
                        type: PathPrefix
                        value: /v1
    - repoURL: https://github.com/Accurate0/inf-k8s.git
      name: application
      path: projects/home-gateway/manifests
      kustomize:

  destination:
    server: https://kubernetes.default.svc
    namespace: home-gateway
operation:
  initiatedBy:
    username: github-actions
  sync:
    prune: true
    syncStrategy:
      hook: {}
