# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/kanidmgroup_v1.json
apiVersion: inf-k8s.net/v1
kind: KanidmGroup
metadata:
  name: flipt-users
  namespace: kanidm
spec:
  name: flipt_users
  members:
    - platform_admins
