# yaml-language-server: $schema=https://k8s-schemas.anurag.sh/inf-k8s.net/kanidmgroup_v1.json
apiVersion: inf-k8s.net/v1
kind: KanidmGroup
metadata:
  name: home-gateway-admins
  namespace: kanidm
spec:
  name: home_gateway_admins
  members:
    - anurag
