apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: crowdsec-secrets
  namespace: crowdsec
spec:
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 900
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: crowd-sec-fatm
        envSlug: prod
        secretsPath: "/"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: crowdsec-managed-secrets
      secretNamespace: crowdsec
      secretType: Opaque
      creationPolicy: "Owner"
