apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../client-policy
patches:
  - target:
      kind: ClientTrafficPolicy
      name: public-gateway-client-policy
    patch: |-
      - op: replace
        path: /metadata/name
        value: git-anurag-sh-client-policy
      - op: add
        path: /spec/targetRefs/0/sectionName
        value: git-anurag-sh-https
      - op: add
        path: /spec/path
        value:
          escapedSlashesAction: KeepUnchanged
