# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backend.policy.yaml
  - ./database.yaml
  - ./anubis.yaml
  - ./kanidmoauth2client.yaml
configMapGenerator:
  - name: forgejo-themes
    files:
      - themes/theme-anthracite.css
      - themes/theme-anthracite-dark.css
      - themes/theme-anthracite-light.css
  - name: forgejo-anubis-policy
    files:
      - botPolicies.yaml=anubis-policy.yaml
  - name: forgejo-kanidm-icon
    files:
      - Forgejo.svg
generatorOptions:
  disableNameSuffixHash: true
