# SPDX-License-Identifier: MIT-0
---
# tasks file for proxy
- name: Setup Proxy
  become: true
  become_user: root
  become_method: sudo
  block:
    - name: Install Packages
      ansible.builtin.apt:
        package:
          - haproxy
          - nginx
          - libnginx-mod-stream
      notify:
        - Start HAProxy

    - name: Get tailscale ip
      ansible.builtin.command: "tailscale ip -4"
      register: tailscale_ip_result
      tags:
        - skip_ansible_lint

    - name: Copy allowed-domains.txt
      ansible.builtin.copy:
        src: allowed-domains.txt
        dest: /etc/haproxy/allowed-domains.txt
        owner: root
        mode: "0644"
      notify:
        - Reload Haproxy

    - name: Create haproxy systemd override directory
      ansible.builtin.file:
        path: /etc/systemd/system/haproxy.service.d
        state: directory
        owner: root
        mode: "0755"

    - name: Template and copy haproxy systemd override
      ansible.builtin.template:
        src: haproxy-override.conf
        dest: /etc/systemd/system/haproxy.service.d/override.conf
        owner: root
        mode: "0644"
      notify:
        - Reload systemd and restart Haproxy

    - name: Template and copy haproxy config
      ansible.builtin.template:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        mode: "0644"
        validate: "haproxy -f %s -c"
      notify:
        - Reload Haproxy

    - name: Setup alternate SSH port
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port 2222"
      notify: "Restart sshd"
