apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: envoy-gateway-system
spec:
  mergeGateways: true
  provider:
    type: "Kubernetes"
    kubernetes:
      envoyDaemonSet:
        patch:
          value:
            metadata:
              labels:
                argocd.argoproj.io/tracking-id: envoy-gateway:apps/DaemonSet:envoy-gateway-system/envoy-proxy
            spec:
              template:
                spec:
                  nodeSelector:
                    inf-k8s.net/proxy: "true"
