# SPDX-License-Identifier: MIT-0
---
# tasks file for required-packages
- name: Install required packages
  become: true
  become_user: root
  block:
    - name: Install Packages
      ansible.builtin.apt:
        package:
          - nfs-common
          - htop
          - neovim
          - zfsutils-linux
