apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-config-managed-secret
  namespace: renovate
spec:
  refreshInterval: 900s
  secretStoreRef:
    name: infisical-renovate-config-secret
    kind: ClusterSecretStore
  target:
    name: renovate-config-managed-secret
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - find:
        name:
          regexp: ".*"
