apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: images-maccas-route
spec:
  hostnames:
    - images.maccas.one
  parentRefs:
    - name: shared-gateway
      namespace: envoy-gateway-system
  rules:
    - backendRefs:
        - name: minio
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: HTTPRouteFilter
            name: rewrite-path-to-bucket
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: rewrite-path-to-bucket
spec:
  urlRewrite:
    path:
      type: ReplaceRegexMatch
      replaceRegexMatch:
        pattern: "/(.*)"
        substitution: '/maccas-images/\1'
