name: Branch build feature-flags
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - platform-services/feature-flags/**
      - "!platform-services/feature-flags/web"
      - crates/feature-flag/feature-flag-proto/**
      - crates/feature-flag/feature-flag-engine/**
      - .github/workflows/branch-build-feature-flags.yaml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4
      - uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7
        with:
          context: .
          file: ./platform-services/feature-flags/Dockerfile
          push: false

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:18@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: feature_flags
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/feature_flags
      SQLX_OFFLINE: "true"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: cargo test (service)
        run: cargo test
        working-directory: platform-services/feature-flags
      - name: cargo test (crates)
        run: cargo test
        working-directory: crates/feature-flag
