name: Branch build feature-flags
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - platform-services/feature-flags/**
      - "!platform-services/feature-flags/web"
      - crates/feature-flag/feature-flag-proto/**
      - crates/feature-flag/feature-flag-engine/**
      - .github/workflows/branch-build-feature-flags.yaml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
      - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: .
          file: ./platform-services/feature-flags/Dockerfile
          push: false

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:18@sha256:b913fd5699b8bd23fa4b06d72ecdd939fad43b80fb8651bac06caa0e6d135cac
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: feature_flags
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/feature_flags
      SQLX_OFFLINE: "true"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Install rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: cargo test (service)
        run: cargo test
        working-directory: platform-services/feature-flags
      - name: cargo test (crates)
        run: cargo test
        working-directory: crates/feature-flag
