name: Build & deploy janitor-bot
on:
  push:
    branches:
      - main
    paths:
      - components/janitor-bot/**
      - .github/workflows/build-deploy-janitor-bot.yaml
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@main
    with:
      directory: ./components/janitor-bot
      image-name: janitor-bot
      docker-build-args: |
        BINARY_NAME=janitor-bot
      use-rust-caching: true

  deploy:
    needs:
      - build
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@main
    with:
      service-name: janitor-bot
      images: ghcr.io/accurate0/janitor-bot
      manifests-path: projects/janitor-bot/manifests
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
