name: Build & deploy pg-db-controller
on:
  push:
    branches:
      - main
    paths:
      - platform-services/pg-db-controller/**
      - '!platform-services/pg-db-controller/manifests/**'
      - '!platform-services/pg-db-controller/application.yaml'
      - .github/workflows/build-deploy-pg-db-controller.yaml
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@1daec34b2444f1c75a17f58ed0a70a148c0def3b # main
    with:
      directory: ./platform-services/pg-db-controller
      image-name: pg-db-controller
      docker-build-args: |
        BINARY_NAME=pg-db-controller
      use-rust-caching: true

  deploy:
    needs:
      - build
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@1daec34b2444f1c75a17f58ed0a70a148c0def3b # main
    with:
      service-name: pg-db-controller
      images: ghcr.io/accurate0/pg-db-controller
      manifests-path: platform-services/pg-db-controller/manifests
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
