name: Build & deploy janitor-bot
on:
  push:
    branches:
      - main
    paths:
      - platform-services/janitor-bot/**
      - '!platform-services/janitor-bot/manifests/**'
      - '!platform-services/janitor-bot/application.yaml'
      - .github/workflows/build-deploy-janitor-bot.yaml
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@95dcf6b102fdaecdc3befae3831b99b3f09ea177 # main
    with:
      directory: ./platform-services/janitor-bot
      image-name: janitor-bot
      docker-build-args: |
        BINARY_NAME=janitor-bot
      use-rust-caching: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Install argocd CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: platform-services/janitor-bot/target
          key: ${{ runner.os }}-app-target-${{ hashFiles('**/Cargo.lock') }}-janitor-bot
      - run: cargo test
        working-directory: platform-services/janitor-bot

  deploy:
    needs:
      - build
      - test
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@95dcf6b102fdaecdc3befae3831b99b3f09ea177 # main
    with:
      service-name: janitor-bot
      images: ghcr.io/accurate0/janitor-bot
      manifests-path: platform-services/janitor-bot/manifests
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
