name: Build & deploy ai-gateway
on:
  push:
    branches:
      - main
    paths:
      - platform-services/ai-gateway/**
      - "!platform-services/ai-gateway/manifests/**"
      - "!platform-services/ai-gateway/application.yaml"
      - crates/**
      - .github/workflows/build-deploy-ai-gateway.yaml
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@cb53fcb62f58d8a064a8913603d6cc28bebc84a6 # main
    with:
      directory: ./platform-services/ai-gateway
      image-name: ai-gateway
      docker-build-args: |
        BINARY_NAME=ai-gateway
      use-rust-caching: true

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: timescale/timescaledb:latest-pg17@sha256:154f1b3915ed050116a85985d5ae1005c8d8bf1562541dc61159610bc05db9a0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ai_gateway
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/ai_gateway
      SQLX_OFFLINE: "true"
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: platform-services/ai-gateway/target
          key: ${{ runner.os }}-app-target-${{ hashFiles('**/Cargo.lock') }}-ai-gateway
      - run: cargo test
        working-directory: platform-services/ai-gateway

  deploy:
    needs:
      - build
      - test
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@cb53fcb62f58d8a064a8913603d6cc28bebc84a6 # main
    with:
      service-name: ai-gateway
      images: ghcr.io/accurate0/ai-gateway
      manifests-path: platform-services/ai-gateway/manifests
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
