name: Build & deploy janitor-bot
on:
  push:
    branches:
      - main
    paths:
      - platform-services/janitor-bot/**
      - "!platform-services/janitor-bot/manifests/**"
      - "!platform-services/janitor-bot/application.yaml"
      - .github/workflows/build-deploy-janitor-bot.yaml
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write

    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@d5901e9bdd4392143298bc1a85e25f33096110f9 # main
    with:
      directory: ./platform-services/janitor-bot
      image-name: janitor-bot
      docker-build-args: |
        BINARY_NAME=janitor-bot
      use-rust-caching: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - name: Install argocd CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: platform-services/janitor-bot/target
          key: ${{ runner.os }}-app-target-${{ hashFiles('**/Cargo.lock') }}-janitor-bot
      - run: cargo test
        working-directory: platform-services/janitor-bot

  deploy:
    needs:
      - build
      - test
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@d5901e9bdd4392143298bc1a85e25f33096110f9 # main
    with:
      service-name: janitor-bot
      images: ghcr.io/accurate0/janitor-bot
      manifests-path: platform-services/janitor-bot/manifests
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
