name: Build & deploy ingress-home
on:
  push:
    branches:
      - main
    paths:
      - platform-services/ingress-home/**
      - '!platform-services/ingress-home/manifests/**'
      - '!platform-services/ingress-home/application.yaml'
      - .github/workflows/build-deploy-ingress-home.yaml
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write
    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@95dcf6b102fdaecdc3befae3831b99b3f09ea177 # main
    with:
      directory: ./platform-services/ingress-home
      image-name: ingress-home
      docker-build-args: |
        BINARY_NAME=ingress-home
      use-rust-caching: true

  deploy:
    needs:
      - build
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@95dcf6b102fdaecdc3befae3831b99b3f09ea177 # main
    with:
      service-name: ingress-home
      images: ghcr.io/accurate0/ingress-home
      manifests-path: platform-services/ingress-home/manifests
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
