name: Build & deploy feature-flags
on:
  push:
    branches:
      - main
    paths:
      - platform-services/feature-flags/**
      - "!platform-services/feature-flags/manifests/**"
      - "!platform-services/feature-flags/application.yaml"
      - "!platform-services/feature-flags/web/**"
      - crates/feature-flag/feature-flag-proto/**
      - crates/feature-flag/feature-flag-engine/**
      - .github/workflows/build-deploy-feature-flags.yaml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          file: ./platform-services/feature-flags/Dockerfile
          push: true
          tags: ghcr.io/accurate0/feature-flags:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:18@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: feature_flags
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/feature_flags
      SQLX_OFFLINE: "true"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: platform-services/feature-flags/target
          key: ${{ runner.os }}-app-target-${{ hashFiles('**/Cargo.lock') }}-feature-flags
      - name: cargo test (service)
        run: cargo test
        working-directory: platform-services/feature-flags
      - name: cargo test (crates)
        run: cargo test
        working-directory: crates/feature-flag

  deploy:
    needs:
      - build
      - test
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@cb53fcb62f58d8a064a8913603d6cc28bebc84a6 # main
    with:
      service-name: feature-flags
      images: ghcr.io/accurate0/feature-flags
      manifests-path: platform-services/feature-flags/manifests
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
