name: Build & deploy ingress-home
on:
  push:
    branches:
      - main
    paths:
      - components/ingress-home/**
      - .github/workflows/build-deploy-ingress-home.yaml
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write
    uses: Accurate0/workflows/.github/workflows/build-push-docker.yaml@main
    with:
      directory: ./components/ingress-home
      image-name: ingress-home
      docker-build-args: |
        BINARY_NAME=ingress-home
      use-rust-caching: true

  deploy:
    needs:
      - build
    uses: Accurate0/workflows/.github/workflows/deploy-app-k8s-v2.yaml@main
    with:
      service-name: ingress-home
      images: ghcr.io/accurate0/ingress-home
      tag: ${{ github.sha }}
    secrets:
      FORGEJO_TOKEN: ${{ secrets.FORGEJO_CI_IMAGE_UPDATER }}
