name: Helm Publish
on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - .github/workflows/publish-helm-charts.yaml

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Push Helm Chart to forgejo
        uses: bsord/helm-push@4.1.0
        with:
          username: anurag
          password: ${{ secrets.FORGEJO_PAT }}
          registry-url: "https://git.anurag.sh/api/packages/anurag/helm"
          force: false
          chart-folder: charts

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.HELM_PAT_TOKEN }}"
