name: Random Test

on:
  workflow_dispatch:
    inputs:
      should_pass:
        description: 'Should the test pass?'
        required: true
        type: boolean
        default: true

jobs:
  random-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: |
          if [ "${{ inputs.should_pass }}" = "true" ]; then
            echo "Test passed."
          else
            echo "Test failed."
            exit 1
          fi
