name: Renovate
on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          configurationFile: platform-services/renovate/config.js
          token: ${{ secrets.FORGEJO_RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: https://git.anurag.sh
          RENOVATE_AUTODISCOVER: "true"
          GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
