name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    container: ghcr.io/renovatebot/renovate:40
    steps:
      - uses: actions/checkout@v4
      - run: renovate
        env:
          RENOVATE_CONFIG_FILE: components/renovate/config.js
          LOG_LEVEL: info
          RENOVATE_TOKEN: ${{ secrets.FORGEJO_RENOVATE_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.GITHUB_COM_TOKEN }}
